CREATE TABLE RULE (
	id_rule INTEGER,
	name VARCHAR(50),
	detail TEXT,
	pack INTEGER,
	PRIMARY KEY (id_rule)
);

CREATE TABLE SENTENCE (
	id_sen INTEGER,
	detail VARCHAR(50),
	ok VARCHAR(50),
	nope TEXT,
	id_rule INTEGER,
	PRIMARY KEY (id_sen)
);

INSERT INTO RULE(ID_RULE, NAME) VALUES (1, 'TOTO');